In [22]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [23]:
df = pd.read_excel("Ml_student_data.xlsx")

In [24]:
df

,student_id,study,Attendence,Previous Marks,Practice,sleep,Learning,Pressure,Environment,Final marks
0,SO1,6.0,88,72,3.5,7.0,8,7,8,79
1,SO2,8.0,94,81,5.0,7.5,7,8,9,88
2,SO3,4.0,76,65,2.0,6.0,6,5,6,67
3,SO4,7.0,91,78,4.0,6.5,9,6,7,84
4,SO5,9.0,97,88,6.0,8.0,8,9,9,94
5,SO6,5.0,82,70,2.5,7.0,5,6,7,72
6,SO7,3.0,71,58,1.5,6.5,7,4,5,61
7,SO8,7.5,89,74,5.0,7.5,9,8,8,87
8,SO9,5.5,85,68,3.0,5.5,6,7,6,73
9,SO10,8.5,92,79,4.5,6.0,7,6,8,85
10,SO11,4.5,79,62,3.5,8.0,8,8,9,76
11,SO12,6.5,86,75,3.0,7.0,6,5,7,76
12,SO13,2.5,68,55,1.0,6.0,5,4,4,56
13,SO14,7.0,95,83,4.5,8.0,8,9,8,91
14,SO15,5.0,90,77,2.0,7.5,9,8,9,84
15,SO16,8.0,84,69,6.0,5.5,8,5,6,80
16,SO17,6.0,73,61,4.0,7.0,7,6,5,70
17,SO18,9.0,90,86,5.5,6.5,9,7,8,91
18,SO19,4.0,88,73,2.5,8.0,6,9,9,79
19,SO20,7.5,81,71,4.0,7.0,8,7,6,81

In [25]:
x = df.drop(columns=["student_id", "Final marks"])
y = df["Final marks"]

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [29]:
y_pred= model.predict(x_test)
y_pred

array([80.78706207, 90.48201507, 77.36728529, 88.39752765])

In [31]:
pd.DataFrame({
    "Feature": x.columns,
    "weight": model.coef_
})

          Feature    weight
0           study  1.849423
1      Attendence  0.235973
2  Previous Marks  0.243729
3        Practice -0.349503
4           sleep  0.662505
5        Learning  1.292792
6        Pressure  1.307624
7     Environment  0.480390

In [32]:
!pip list

Package                   Version
------------------------- -----------
anyio                     4.13.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.5.20
cffi                      2.0.0
charset-normalizer        3.4.7
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.21
decorator                 5.3.1
defusedxml                0.7.1
et_xmlfile                2.0.0
executing                 2.2.1
fastjsonschema            2.21.2
flatbuffers               25.12.19
fonttools                 4.63.0
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.18
ImageIO                   2.37.4
ipykernel                 7.3.0
ipython                   9.14.1
ipython_pygments_lexers   1.1.1
isoduration               20.11.0
jedi                      0.20.0
Jinja2                    3.1.6
joblib                    1.5.3
json5                     0.14.0
jsonpointer               3.1.1
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter_builder           1.2.1
jupyter_client            8.9.1
jupyter_core              5.9.1
jupyter-events            0.12.1
jupyter-lsp               2.3.1
jupyter_server            2.19.0
jupyter_server_terminals  0.5.4
jupyterlab                4.6.2
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
kiwisolver                1.5.0
lark                      1.3.1
lazy-loader               0.5
llvmlite                  0.48.0
MarkupSafe                3.0.3
matplotlib                3.11.1
matplotlib-inline         0.2.2
mistune                   3.2.1
narwhals                  2.24.0
nbclient                  0.11.0
nbconvert                 7.17.1
nbformat                  5.10.4
nest-asyncio2             1.7.2
networkx                  3.6.1
notebook_shim             0.2.4
numba                     0.66.0
numpy                     2.4.6
opencv-python             5.0.0.93
openpyxl                  3.1.5
packaging                 26.2
pandas                    3.0.5
pandocfilters             1.5.1
parso                     0.8.7
pillow                    12.3.0
pip                       26.2
platformdirs              4.10.0
pooch                     1.9.0
prometheus_client         0.25.0
prompt_toolkit            3.0.52
protobuf                  7.35.1
psutil                    7.2.2
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.20.0
PyMatting                 1.1.15
pyparsing                 3.3.2
python-dateutil           2.9.0.post0
python-json-logger        4.1.0
pywinpty                  3.0.4
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.34.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   2026.5.1
scikit-image              0.26.0
scikit-learn              1.9.0
scipy                     1.18.0
Send2Trash                2.1.0
setuptools                82.0.1
six                       1.17.0
soupsieve                 2.8.4
stack-data                0.6.3
terminado                 0.18.1
threadpoolctl             3.6.0
tifffile                  2026.7.31
tinycss2                  1.5.1
tornado                   6.5.7
tqdm                      4.70.0
traitlets                 5.15.1
typing_extensions         4.15.0
tzdata                    2026.2
uri-template              1.3.0
urllib3                   2.7.0
wcwidth                   0.8.1
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0

In [33]:
!pip uninstall scikit-learn -y

Found existing installation: scikit-learn 1.9.0
Uninstalling scikit-learn-1.9.0:
  Successfully uninstalled scikit-learn-1.9.0

WARNING: Failed to remove contents in a temporary directory 'C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages\~klearn'.
You can safely remove it manually.